const test=require('node:test');const assert=require('node:assert/strict');const {DatabaseSync}=require('node:sqlite');
const evidenceApi=require('../MLS R32 EDITORIAL/evidence api.js');const claims=require('../MLS R32 EDITORIAL/evidence claims.js');
function setup(){
 const db=new DatabaseSync(':memory:');
 db.exec("CREATE TABLE wiki_articles(code TEXT PRIMARY KEY,language TEXT,language_name TEXT,n INTEGER,title TEXT,level TEXT,part TEXT,chapter TEXT,article_markdown TEXT NOT NULL,provider TEXT,model TEXT,audit_provider TEXT,audit_model TEXT,prompt_version TEXT,generated_at TEXT NOT NULL)");
 db.prepare("INSERT INTO wiki_articles(code,language,language_name,n,title,level,part,chapter,article_markdown,prompt_version,generated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)").run('MLS-V10-0020','espanol-guatemala','Español',20,'Gerundio de leer','A1','Fundamentos','Verbos','#### Regla\nLeer forma leyendo.','32.0','2026-09-21T10:00:00Z');
 const wrap=(sql,args=[])=>({sql,args,bind(...x){return wrap(sql,x)},async first(){return db.prepare(sql).get(...args)||null},async all(){return {results:db.prepare(sql).all(...args)}},async run(){const r=db.prepare(sql).run(...args);return {meta:{changes:Number(r.changes)}}}});
 const WIKI_DB={prepare:wrap,async batch(stmts){db.exec('BEGIN');try{const x=stmts.map(q=>{const r=db.prepare(q.sql).run(...q.args);return {meta:{changes:Number(r.changes)}}});db.exec('COMMIT');return x}catch(e){db.exec('ROLLBACK');throw e}}};
 const runtime={authenticate:async req=>{if(req.headers.get('authorization')!=='Bearer test') {const e=new Error('Autenticación requerida.');e.status=401;throw e;}},ensureWikiDb:async()=>{},body:async req=>req.json(),json:(data,status=200)=>Response.json(data,{status}),error:(status,message)=>{const e=new Error(message);e.status=status;throw e;}};
 return {db,env:{WIKI_DB},runtime};
}
async function call(s,path,{method='GET',body}={}){const init={method,headers:{authorization:'Bearer test'}};if(body!==undefined){init.headers['content-type']='application/json';init.body=JSON.stringify(body);}const req=new Request('https://example.test'+path,init);return evidenceApi.handleMlsEvidence(req,s.env,new URL(req.url),s.runtime);}
async function json(res){return {status:res.status,body:await res.json()};}
async function version(s){return claims.currentArticleVersion(s.env,'MLS-V10-0020');}
function proposal(v,expectedEvidenceRevision=0){return {code:v.code,articleGeneratedAt:v.articleGeneratedAt,articleHash:v.articleHash,expectedEvidenceRevision,sources:[{clientId:'src1',sourceType:'report',authorityTier:'A',title:'Norma institucional',institution:'Institución',publicationYear:2025}],claims:[{clientId:'cl1',sectionKey:'Regla',summary:'Leer forma leyendo.',claimType:'normative',materiality:'substantial'}],links:[{claimRef:'cl1',sourceRef:'src1',supportType:'supports',verificationMethod:'manual_source_match'}],conflicts:[]};}

test('evidence api: authentication is required',async()=>{const s=setup();const req=new Request('https://example.test/api/wiki/editorial/evidence/status');const res=await evidenceApi.handleMlsEvidence(req,s.env,new URL(req.url),s.runtime);assert.equal(res.status,401);});
test('evidence api: status starts empty and FREE ONLY',async()=>{const s=setup();const r=await json(await call(s,'/api/wiki/editorial/evidence/status'));assert.equal(r.status,200);assert.equal(r.body.freeOnly,true);assert.equal(r.body.zeroCost,true);assert.equal(r.body.sourceRegistry.total,0);});
test('evidence api: entry returns canonical article and UNSOURCED state',async()=>{const s=setup();const r=await json(await call(s,'/api/wiki/editorial/evidence/entry?code=MLS-V10-0020'));assert.equal(r.status,200);assert.equal(r.body.article.code,'MLS-V10-0020');assert.equal(r.body.evaluation.status,'UNSOURCED');assert.match(r.body.version.articleHash,/^[a-f0-9]{64}$/);});
test('evidence api: proposal persists Evidence and increments state revision',async()=>{const s=setup(),v=await version(s);const r=await json(await call(s,'/api/wiki/editorial/evidence/proposal',{method:'POST',body:proposal(v)}));assert.equal(r.status,200);assert.equal(r.body.state.evidence_revision,1);assert.equal(r.body.state.status,'SOURCED');assert.ok(r.body.mappings.sources.src1.startsWith('MLS-SRC-'));assert.ok(r.body.mappings.claims.cl1.startsWith('MLS-CLM-'));});
test('evidence api: validate is read-only and reports canVerify',async()=>{const s=setup(),v=await version(s);await call(s,'/api/wiki/editorial/evidence/proposal',{method:'POST',body:proposal(v)});const before=s.db.prepare('SELECT evidence_revision FROM wiki_evidence_entry_state WHERE code=?').get(v.code).evidence_revision;const r=await json(await call(s,'/api/wiki/editorial/evidence/validate',{method:'POST',body:{code:v.code}}));assert.equal(r.status,200);assert.equal(r.body.canVerify,true);assert.equal(r.body.assessment.citationReady,true);assert.equal(s.db.prepare('SELECT evidence_revision FROM wiki_evidence_entry_state WHERE code=?').get(v.code).evidence_revision,before);});
test('evidence api: verify then review uses persisted reviews and revisions',async()=>{const s=setup(),v=await version(s);await call(s,'/api/wiki/editorial/evidence/proposal',{method:'POST',body:proposal(v)});let r=await json(await call(s,'/api/wiki/editorial/evidence/verify',{method:'POST',body:{code:v.code,expectedEvidenceRevision:1,reviewerType:'chatgpt',runId:'test-run'}}));assert.equal(r.status,200);assert.equal(r.body.status,'VERIFIED');assert.equal(r.body.state.evidence_revision,2);r=await json(await call(s,'/api/wiki/editorial/evidence/review',{method:'POST',body:{code:v.code,expectedEvidenceRevision:2,reviewerType:'human',reviewer:'Revisor'}}));assert.equal(r.status,200);assert.equal(r.body.status,'REVIEWED');assert.equal(r.body.state.evidence_revision,3);assert.equal(s.db.prepare('SELECT COUNT(*) n FROM wiki_evidence_reviews').get().n,2);});
test('evidence api: stale Evidence revision returns 409',async()=>{const s=setup(),v=await version(s);await call(s,'/api/wiki/editorial/evidence/proposal',{method:'POST',body:proposal(v)});const r=await json(await call(s,'/api/wiki/editorial/evidence/proposal',{method:'POST',body:proposal(v,0)}));assert.equal(r.status,409);assert.equal(r.body.code,'EVIDENCE_REVISION_CONFLICT');});
test('evidence api: unknown link refs fail before evidence writes',async()=>{const s=setup(),v=await version(s),p=proposal(v);p.links[0].sourceRef='missing';const r=await json(await call(s,'/api/wiki/editorial/evidence/proposal',{method:'POST',body:p}));assert.equal(r.status,422);assert.equal(r.body.code,'UNKNOWN_SOURCE_REF');assert.equal(s.db.prepare('SELECT COUNT(*) n FROM wiki_sources').get().n,0);assert.equal(s.db.prepare('SELECT COUNT(*) n FROM wiki_evidence_claims').get().n,0);});
test('evidence api: source listing includes generated APA reference',async()=>{const s=setup(),v=await version(s);await call(s,'/api/wiki/editorial/evidence/proposal',{method:'POST',body:proposal(v)});const r=await json(await call(s,'/api/wiki/editorial/evidence/sources?code='+v.code));assert.equal(r.status,200);assert.equal(r.body.sources.length,1);assert.equal(r.body.sources[0].citation.citationReady,true);assert.match(r.body.sources[0].citation.markdown,/Norma institucional/);});
test('evidence api: revision proposal never overwrites canonical article',async()=>{const s=setup(),v=await version(s),before=s.db.prepare('SELECT article_markdown FROM wiki_articles WHERE code=?').get(v.code).article_markdown;const r=await json(await call(s,'/api/wiki/editorial/evidence/revision/propose',{method:'POST',body:{code:v.code,expectedArticleHash:v.articleHash,articleMarkdown:'#### Regla\nLeer forma *leyendo*.',changeReason:'Corrección Evidence'}}));assert.equal(r.status,200);assert.equal(r.body.revision.status,'proposed');assert.equal(s.db.prepare('SELECT article_markdown FROM wiki_articles WHERE code=?').get(v.code).article_markdown,before);});

test('evidence api: entry returns the real language source policy',async()=>{const s=setup();const r=await json(await call(s,'/api/wiki/editorial/evidence/entry?code=MLS-V10-0020'));assert.equal(r.status,200);assert.equal(r.body.policy.language,'espanol-guatemala');assert.deepEqual(r.body.policy.approvedSourcePool,[]);});
test('evidence api: provenance endpoint composes R32 and R33 without public mutation',async()=>{const s=setup();const r=await json(await call(s,'/api/wiki/editorial/evidence/provenance?code=MLS-V10-0020'));assert.equal(r.status,200);assert.equal(r.body.provenance.system.repository,'dpidiaz/llmchatmls');assert.equal(r.body.provenance.r33.effectiveStatus,'UNSOURCED');});

test('evidence api: responses expose D1 telemetry without inventing billed rows',async()=>{const s=setup();const r=await json(await call(s,'/api/wiki/editorial/evidence/status'));assert.equal(r.status,200);assert.ok(r.body.telemetry?.d1);assert.equal(r.body.telemetry.d1.d1RowsRead,null);assert.equal(r.body.telemetry.d1.exactRowsRead,false);assert.ok(r.body.telemetry.d1.observedRowsRead>=0);});
test('evidence api: proposal reports Source creation and later reuse explicitly',async()=>{const s=setup(),v=await version(s);let r=await json(await call(s,'/api/wiki/editorial/evidence/proposal',{method:'POST',body:proposal(v,0)}));assert.equal(r.body.operations.sourcesCreated,1);assert.equal(r.body.operations.sourcesReused,0);assert.equal(r.body.operations.claimsCreated,1);assert.equal(r.body.operations.linksCreated,1);r=await json(await call(s,'/api/wiki/editorial/evidence/proposal',{method:'POST',body:proposal(v,1)}));assert.equal(r.status,200);assert.equal(r.body.operations.sourcesCreated,0);assert.equal(r.body.operations.sourcesReused,1);assert.equal(r.body.operations.claimsReused,1);assert.equal(r.body.operations.linksReused,1);});
test('evidence api: metrics endpoint reports logical Evidence bytes read-only',async()=>{const s=setup(),v=await version(s);await call(s,'/api/wiki/editorial/evidence/proposal',{method:'POST',body:proposal(v)});const before=s.db.prepare('SELECT evidence_revision FROM wiki_evidence_entry_state WHERE code=?').get(v.code).evidence_revision;const r=await json(await call(s,'/api/wiki/editorial/evidence/metrics?code='+v.code));assert.equal(r.status,200);assert.ok(r.body.storage.logicalEvidenceBytes>0);assert.equal(r.body.storage.rowCounts.claims,1);assert.ok(r.body.telemetry?.d1);assert.equal(s.db.prepare('SELECT evidence_revision FROM wiki_evidence_entry_state WHERE code=?').get(v.code).evidence_revision,before);});

test('evidence api: container DOI survives Source Registry roundtrip without becoming granular identity',async()=>{
  const s=setup(),v=await version(s);
  const p={
    code:v.code,articleGeneratedAt:v.articleGeneratedAt,articleHash:v.articleHash,expectedEvidenceRevision:0,
    sources:[{clientId:'src1',sourceType:'institutional_webpage',authorityTier:'A',title:'laut',institution:'IDS grammis',doi:'10.14618/wb-praepositionen',doiScope:'container',canonicalUrl:'https://grammis.ids-mannheim.de/praepositionen/299306'}],
    claims:[{clientId:'cl1',sectionKey:'Regla',summary:'Claim granular.',claimType:'general',materiality:'substantial'}],
    links:[{claimRef:'cl1',sourceRef:'src1',supportType:'supports',verificationMethod:'manual_source_match'}],
    conflicts:[]
  };
  const created=await json(await call(s,'/api/wiki/editorial/evidence/proposal',{method:'POST',body:p}));
  assert.equal(created.status,200);
  const listed=await json(await call(s,'/api/wiki/editorial/evidence/sources?code='+v.code));
  assert.equal(listed.status,200);
  assert.equal(listed.body.sources.length,1);
  assert.equal(listed.body.sources[0].source.doi,'10.14618/wb-praepositionen');
  assert.equal(listed.body.sources[0].source.doiScope,'container');
  assert.equal(listed.body.sources[0].source.identityKind,'url');
  assert.equal(listed.body.sources[0].citation.url,'https://grammis.ids-mannheim.de/praepositionen/299306');
});

test('evidence api: consumer endpoint is read-only and conservative for UNSOURCED',async()=>{const s=setup();const r=await json(await call(s,'/api/wiki/editorial/evidence/consumer?code=MLS-V10-0020'));assert.equal(r.status,200);assert.equal(r.body.evidence.status,'UNSOURCED');assert.match(r.body.evidence.disclosure,/fundamentación bibliográfica/);});

test('evidence api: reuse candidates endpoint is read-only and never auto-approves',async()=>{const s=setup();const r=await json(await call(s,'/api/wiki/editorial/evidence/reuse-candidates',{method:'POST',body:{language:'espanol-guatemala',topics:['gerundio'],limit:5}}));assert.equal(r.status,200);assert.equal(r.body.contract.approved,false);assert.equal(r.body.telemetry.d1.d1RowsWritten,null);});
test('evidence api: batch triage remains non-authorizing',async()=>{const s=setup();const r=await json(await call(s,'/api/wiki/editorial/evidence/triage',{method:'POST',body:{entries:[{code:'MLS-V10-0020',topics:['gerundio']}],candidateLimit:5}}));assert.equal(r.status,200);assert.equal(r.body.requested,1);assert.equal(r.body.gate100Authorized,false);assert.equal(r.body.items[0].lane,'needs_evidence');assert.equal(r.body.telemetry.d1.d1RowsWritten,null);});
