const test=require('node:test');const assert=require('node:assert/strict');const {DatabaseSync}=require('node:sqlite');
const registry=require('../MLS R32 EDITORIAL/evidence registry.js');const claims=require('../MLS R32 EDITORIAL/evidence claims.js');const validator=require('../MLS R32 EDITORIAL/evidence validator.js');const scale=require('../MLS R32 EDITORIAL/evidence scale.js');
function setup(){
 const db=new DatabaseSync(':memory:');
 db.exec("CREATE TABLE wiki_articles(code TEXT PRIMARY KEY,language TEXT,language_name TEXT,n INTEGER,title TEXT,level TEXT,part TEXT,chapter TEXT,article_markdown TEXT NOT NULL,provider TEXT,model TEXT,audit_provider TEXT,audit_model TEXT,prompt_version TEXT,generated_at TEXT NOT NULL)");
 const ins=db.prepare("INSERT INTO wiki_articles(code,language,language_name,n,title,level,part,chapter,article_markdown,prompt_version,generated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)");
 ins.run('MLS-V05-0001','aleman','Alemán',1,'Präpositionen mit Dativ','B1','Grammatik','Präpositionen','Text uno','32.0','2026-09-21T10:00:00Z');
 ins.run('MLS-V05-0002','aleman','Alemán',2,'Dativ nach Präpositionen','B1','Grammatik','Präpositionen','Text dos','32.0','2026-09-21T10:01:00Z');
 ins.run('MLS-V05-0003','aleman','Alemán',3,'Aussprache und Vokale','A2','Aussprache','Vokale','Text tres','32.0','2026-09-21T10:02:00Z');
 const stats={candidatePoolQueries:0};
 const wrap=(sql,args=[])=>({sql,args,bind(...x){return wrap(sql,x)},async first(){return db.prepare(sql).get(...args)||null},async all(){if(sql.includes('COUNT(DISTINCT c.code) AS entry_usage'))stats.candidatePoolQueries+=1;return {results:db.prepare(sql).all(...args)}},async run(){const r=db.prepare(sql).run(...args);return {meta:{changes:Number(r.changes)}}}});
 const WIKI_DB={prepare:wrap,async batch(stmts){db.exec('BEGIN');try{const out=stmts.map(x=>{const r=db.prepare(x.sql).run(...x.args);return {meta:{changes:Number(r.changes)}}});db.exec('COMMIT');return out}catch(e){db.exec('ROLLBACK');throw e}}};
 return {db,env:{WIKI_DB},stats};
}
async function seedSource(s,code='MLS-V05-0001'){
 await registry.ensureEvidenceDb(s.env);
 const v=await claims.currentArticleVersion(s.env,code);
 const src=(await registry.upsertSource(s.env,{sourceType:'institutional_webpage',authorityTier:'A',title:'Präpositionen und Rektion',institution:'IDS',url:'https://example.org/praepositionen',language:'de',topics:['Präpositionen','Dativ','Rektion']})).source;
 const cl=(await claims.upsertClaim(s.env,{...v,summary:'Präpositionen können den Dativ regieren.',claimType:'normative',materiality:'substantial'})).claim;
 await claims.upsertEvidenceLink(s.env,{claimId:cl.claim_id,sourceId:src.sourceId,supportType:'supports'});
 return {v,src,cl};
}
test('scale prep: reusable pool returns candidates but never approved sources',async()=>{const s=setup();const {src}=await seedSource(s);const r=await scale.reusableSourceCandidates(s.env,{language:'aleman',topics:['Dativ'],limit:10});assert.equal(r.candidateCount,1);assert.equal(r.candidates[0].source.sourceId,src.sourceId);assert.equal(r.candidates[0].approved,false);assert.equal(r.candidates[0].reuseStatus,'candidate_only');assert.equal(r.candidates[0].requiresClaimSpecificVerification,true);});
test('scale prep: unrelated topics require external discovery',async()=>{const s=setup();await seedSource(s);const r=await scale.triageEntry(s.env,{code:'MLS-V05-0003',topics:['fonología']});assert.equal(r.lane,'needs_evidence');assert.equal(r.discoveryMode,'external_discovery');assert.equal(r.sourceCandidateCount,0);});
test('scale prep: matching registry evidence routes UNSOURCED entry to registry first',async()=>{const s=setup();await seedSource(s);const r=await scale.triageEntry(s.env,{code:'MLS-V05-0002',topics:['Dativ']});assert.equal(r.status,'UNSOURCED');assert.equal(r.lane,'needs_evidence');assert.equal(r.discoveryMode,'registry_first');assert.equal(r.externalDiscoveryRequired,false);assert.equal(r.sourceCandidateCount,1);});
test('scale prep: SOURCED entry resumes existing evidence instead of restarting discovery',async()=>{const s=setup();await seedSource(s);await seedSource(s,'MLS-V05-0002');const r=await scale.triageEntry(s.env,{code:'MLS-V05-0002',topics:['Dativ']});assert.equal(r.status,'SOURCED');assert.equal(r.lane,'resume_existing');assert.equal(r.discoveryMode,'registry_first');});
test('scale prep: proposed revision routes entry to exception lane',async()=>{const s=setup();await registry.ensureEvidenceDb(s.env);const v=await claims.currentArticleVersion(s.env,'MLS-V05-0002');s.db.prepare("INSERT INTO wiki_article_revisions(revision_id,code,revision_number,article_markdown,article_hash,source_generated_at,change_reason,status,created_at) VALUES(?,?,?,?,?,?,?,?,?)").run('rev1',v.code,1,'propuesta','a'.repeat(64),v.articleGeneratedAt,'review','proposed','2026-09-21T12:00:00Z');const r=await scale.triageEntry(s.env,{code:v.code});assert.equal(r.lane,'exception');assert.equal(r.discoveryMode,'human_or_manual');});
test('scale prep: VERIFIED entry is complete and skips source discovery',async()=>{const s=setup();await seedSource(s,'MLS-V05-0001');const verified=await validator.verifyEntryEvidence(s.env,'MLS-V05-0001',{expectedEvidenceRevision:0,now:'2026-09-21T12:00:00Z'});assert.equal(verified.status,'VERIFIED');const r=await scale.triageEntry(s.env,{code:'MLS-V05-0001'});assert.equal(r.lane,'complete');assert.equal(r.discoveryMode,'none');assert.equal(r.sourceCandidateCount,0);});
test('scale prep: batch triage reuses one candidate pool scan per language',async()=>{const s=setup();await seedSource(s);const r=await scale.batchTriage(s.env,{entries:[{code:'MLS-V05-0002',topics:['Dativ']},{code:'MLS-V05-0003',topics:['fonología']}],candidateLimit:5});assert.equal(r.processed,2);assert.equal(s.stats.candidatePoolQueries,1);});
test('scale prep: batch triage groups lanes and never authorizes Gate 100',async()=>{const s=setup();await seedSource(s);const r=await scale.batchTriage(s.env,{entries:[{code:'MLS-V05-0002',topics:['Dativ']},{code:'MLS-V05-0003',topics:['fonología']}],candidateLimit:5});assert.equal(r.requested,2);assert.equal(r.processed,2);assert.equal(r.byLane.needs_evidence,2);assert.equal(r.byDiscovery.registry_first,1);assert.equal(r.byDiscovery.external_discovery,1);assert.equal(r.gate100Authorized,false);});
test('scale prep: batch is capped at fifty entries',async()=>{const s=setup();const entries=Array.from({length:51},(_,i)=>({code:'MLS-V05-'+String(i+100).padStart(4,'0')}));await assert.rejects(()=>scale.batchTriage(s.env,{entries}),e=>e.code==='INVALID_TRIAGE_BATCH'&&e.status===422);});
test('scale prep: read-only triage creates no Evidence rows after schema is initialized',async()=>{const s=setup();await registry.ensureEvidenceDb(s.env);const before={sources:s.db.prepare('SELECT COUNT(*) n FROM wiki_sources').get().n,claims:s.db.prepare('SELECT COUNT(*) n FROM wiki_evidence_claims').get().n,links:s.db.prepare('SELECT COUNT(*) n FROM wiki_evidence_links').get().n,reviews:s.db.prepare('SELECT COUNT(*) n FROM wiki_evidence_reviews').get().n};await scale.batchTriage(s.env,{entries:[{code:'MLS-V05-0002'}]});const after={sources:s.db.prepare('SELECT COUNT(*) n FROM wiki_sources').get().n,claims:s.db.prepare('SELECT COUNT(*) n FROM wiki_evidence_claims').get().n,links:s.db.prepare('SELECT COUNT(*) n FROM wiki_evidence_links').get().n,reviews:s.db.prepare('SELECT COUNT(*) n FROM wiki_evidence_reviews').get().n};assert.deepEqual(after,before);});
