const test=require('node:test');const assert=require('node:assert/strict');const {DatabaseSync}=require('node:sqlite');
const registry=require('../MLS R32 EDITORIAL/evidence registry.js');const claims=require('../MLS R32 EDITORIAL/evidence claims.js');const validator=require('../MLS R32 EDITORIAL/evidence validator.js');
function setup(){const db=new DatabaseSync(':memory:');db.exec("CREATE TABLE wiki_articles(code TEXT PRIMARY KEY,article_markdown TEXT NOT NULL,generated_at TEXT NOT NULL)");db.prepare("INSERT INTO wiki_articles VALUES(?,?,?)").run('MLS-V10-0020','#### Regla\nLeer forma leyendo.','2026-09-21T10:00:00Z');const wrap=(sql,args=[])=>({sql,args,bind(...x){return wrap(sql,x)},async first(){return db.prepare(sql).get(...args)||null},async all(){return {results:db.prepare(sql).all(...args)}},async run(){const r=db.prepare(sql).run(...args);return {meta:{changes:Number(r.changes)}}}});return {db,env:{WIKI_DB:{prepare:wrap,async batch(stmts){db.exec('BEGIN');try{const x=stmts.map(q=>{const r=db.prepare(q.sql).run(...q.args);return {meta:{changes:Number(r.changes)}}});db.exec('COMMIT');return x}catch(e){db.exec('ROLLBACK');throw e}}}}};}
async function add(s,{claimType='general',tier='A',supportType='supports',locator={},sourceType='report',sourceExtra={}}={}){const v=await claims.currentArticleVersion(s.env,'MLS-V10-0020');const cl=(await claims.upsertClaim(s.env,{...v,summary:'Regla sustancial',claimType,materiality:'substantial'})).claim;const src=(await registry.upsertSource(s.env,{sourceType,authorityTier:tier,title:'Norma '+tier,institution:'Inst '+tier,publicationYear:2025,...sourceExtra})).source;await claims.upsertEvidenceLink(s.env,{claimId:cl.claim_id,sourceId:src.sourceId,supportType,locator});return {v,cl,src};}
test('validator: no mapping is UNSOURCED',async()=>{const s=setup();assert.equal((await validator.evaluateEntryEvidence(s.env,'MLS-V10-0020')).status,'UNSOURCED');});
test('validator: contextual source is SOURCED but not verified coverage',async()=>{const s=setup();await add(s,{supportType:'contextualizes'});const r=await validator.evaluateEntryEvidence(s.env,'MLS-V10-0020');assert.equal(r.status,'SOURCED');assert.equal(r.claimsVerified,0);});
test('validator: APA readiness is computed by backend',async()=>{const s=setup();await add(s,{sourceType:'journal_article'});const r=await validator.evaluateEntryEvidence(s.env,'MLS-V10-0020',{citationReady:true,verificationConfirmed:true});assert.equal(r.status,'SOURCED');assert.equal(r.citationReady,false);assert.ok(r.reasons.includes('apa_validation_required'));});
test('validator: complete coverage stays SOURCED without persisted verification review',async()=>{const s=setup();await add(s);const r=await validator.evaluateEntryEvidence(s.env,'MLS-V10-0020',{verificationConfirmed:true});assert.equal(r.status,'SOURCED');assert.ok(r.reasons.includes('verification_event_missing'));});
test('validator: verifyEntryEvidence records review and produces VERIFIED',async()=>{const s=setup();await add(s);const r=await validator.verifyEntryEvidence(s.env,'MLS-V10-0020',{expectedEvidenceRevision:0,now:'2026-09-21T12:00:00Z',runId:'run-v'});assert.equal(r.status,'VERIFIED');assert.equal(r.state.status,'VERIFIED');assert.equal(r.review.review_kind,'verification');assert.equal(s.db.prepare('SELECT COUNT(*) n FROM wiki_evidence_reviews').get().n,1);});
test('validator: normative claims require strong A/B source by default',async()=>{const s=setup();await add(s,{claimType:'normative',tier:'C'});const r=await validator.evaluateEntryEvidence(s.env,'MLS-V10-0020');assert.equal(r.status,'SOURCED');assert.equal(r.claimsVerified,0);await assert.rejects(()=>validator.verifyEntryEvidence(s.env,'MLS-V10-0020',{expectedEvidenceRevision:0}),e=>e.code==='EVIDENCE_NOT_READY');});
test('validator: quotation policy requires locator',async()=>{const s=setup();await add(s,{claimType:'quotation'});assert.equal((await validator.evaluateEntryEvidence(s.env,'MLS-V10-0020')).claimsVerified,0);const s2=setup();await add(s2,{claimType:'quotation',locator:{page:'4'}});assert.equal((await validator.verifyEntryEvidence(s2.env,'MLS-V10-0020',{expectedEvidenceRevision:0})).status,'VERIFIED');});
test('validator: unresolved substantive contradiction blocks verification',async()=>{const s=setup();const {cl,src}=await add(s);await claims.recordConflict(s.env,{claimId:cl.claim_id,conflictType:'contradiction',context:'Discrepancia.',sourceIds:[src.sourceId]});await assert.rejects(()=>validator.verifyEntryEvidence(s.env,'MLS-V10-0020',{expectedEvidenceRevision:0}),e=>e.code==='EVIDENCE_NOT_READY'&&e.reasons.includes('unresolved_substantive_conflict'));});
test('validator: accepted regional variation does not block verification',async()=>{const s=setup();const {cl,src}=await add(s);await claims.recordConflict(s.env,{claimId:cl.claim_id,conflictType:'regional_variation',status:'accepted_variation',context:'Variación legítima.',resolution:'Se documentan ambas.',sourceIds:[src.sourceId]});assert.equal((await validator.verifyEntryEvidence(s.env,'MLS-V10-0020',{expectedEvidenceRevision:0})).status,'VERIFIED');});
test('validator: state persistence increments revision and rejects stale expected revision',async()=>{const s=setup();await add(s);const a=await validator.persistEvaluation(s.env,'MLS-V10-0020',{expectedEvidenceRevision:0});assert.equal(a.state.evidence_revision,1);const b=await validator.persistEvaluation(s.env,'MLS-V10-0020',{expectedEvidenceRevision:1});assert.equal(b.state.evidence_revision,2);await assert.rejects(()=>validator.persistEvaluation(s.env,'MLS-V10-0020',{expectedEvidenceRevision:1}),e=>e.code==='EVIDENCE_REVISION_CONFLICT'&&e.status===409);});
test('validator: evidence mutation invalidates VERIFIED even when stored state remains VERIFIED',async()=>{const s=setup();const {v}=await add(s);await validator.verifyEntryEvidence(s.env,'MLS-V10-0020',{expectedEvidenceRevision:0,now:'2026-09-21T12:00:00Z'});assert.equal((await validator.effectiveState(s.env,'MLS-V10-0020')).effectiveStatus,'VERIFIED');await claims.upsertClaim(s.env,{...v,summary:'Claim posterior',claimType:'general'});assert.equal((await validator.effectiveState(s.env,'MLS-V10-0020')).effectiveStatus,'SOURCED');});
test('validator: REVIEWED requires a second persisted editorial review',async()=>{const s=setup();await add(s);const verified=await validator.verifyEntryEvidence(s.env,'MLS-V10-0020',{expectedEvidenceRevision:0,now:'2026-09-21T12:00:00Z'});assert.equal(verified.state.evidence_revision,1);const reviewed=await validator.reviewEntryEvidence(s.env,'MLS-V10-0020',{expectedEvidenceRevision:1,now:'2026-09-21T13:00:00Z',reviewerType:'human',reviewer:'Revisor'});assert.equal(reviewed.status,'REVIEWED');assert.equal(reviewed.state.status,'REVIEWED');assert.equal(reviewed.review.review_kind,'editorial_review');assert.equal(s.db.prepare('SELECT COUNT(*) n FROM wiki_evidence_reviews').get().n,2);});
test('validator: editorial review cannot precede verification',async()=>{const s=setup();await add(s);await validator.persistEvaluation(s.env,'MLS-V10-0020',{expectedEvidenceRevision:0});await assert.rejects(()=>validator.reviewEntryEvidence(s.env,'MLS-V10-0020',{expectedEvidenceRevision:1}),e=>e.code==='VERIFIED_REVIEW_REQUIRED');});
test('validator: stale article version becomes UNSOURCED and can reset with expected revision zero',async()=>{const s=setup();await add(s);await validator.persistEvaluation(s.env,'MLS-V10-0020',{expectedEvidenceRevision:0});s.db.prepare("UPDATE wiki_articles SET article_markdown=?,generated_at=? WHERE code=?").run('Texto nuevo','2026-09-22T00:00:00Z','MLS-V10-0020');assert.equal((await validator.effectiveState(s.env,'MLS-V10-0020')).effectiveStatus,'UNSOURCED');const r=await validator.persistEvaluation(s.env,'MLS-V10-0020',{expectedEvidenceRevision:0});assert.equal(r.state.evidence_revision,1);assert.equal(r.state.status,'UNSOURCED');assert.equal(r.state.article_generated_at,'2026-09-22T00:00:00Z');});
