const test=require('node:test');const assert=require('node:assert/strict');const {DatabaseSync}=require('node:sqlite');
const registry=require('../MLS R32 EDITORIAL/evidence registry.js');const claims=require('../MLS R32 EDITORIAL/evidence claims.js');const validator=require('../MLS R32 EDITORIAL/evidence validator.js');
function setup(){const db=new DatabaseSync(':memory:');db.exec("CREATE TABLE wiki_articles(code TEXT PRIMARY KEY,article_markdown TEXT NOT NULL,generated_at TEXT NOT NULL)");db.prepare("INSERT INTO wiki_articles VALUES(?,?,?)").run('MLS-V10-0020','#### Regla\nLeer forma leyendo.','2026-09-21T10:00:00Z');const wrap=(sql,args=[])=>({sql,args,bind(...x){return wrap(sql,x)},async first(){return db.prepare(sql).get(...args)||null},async all(){return {results:db.prepare(sql).all(...args)}},async run(){const r=db.prepare(sql).run(...args);return {meta:{changes:Number(r.changes)}}}});return {db,env:{WIKI_DB:{prepare:wrap,async batch(stmts){db.exec('BEGIN');try{const x=stmts.map(q=>{const r=db.prepare(q.sql).run(...q.args);return {meta:{changes:Number(r.changes)}}});db.exec('COMMIT');return x}catch(e){db.exec('ROLLBACK');throw e}}}}};}
async function add(s,{claimType='general',tier='A',supportType='supports',locator={},sourceType='report',sourceExtra={}}={}){const v=await claims.currentArticleVersion(s.env,'MLS-V10-0020');const cl=(await claims.upsertClaim(s.env,{...v,summary:'Regla sustancial',claimType,materiality:'substantial'})).claim;const src=(await registry.upsertSource(s.env,{sourceType,authorityTier:tier,title:'Norma '+tier,institution:'Inst '+tier,publicationYear:2025,...sourceExtra})).source;await claims.upsertEvidenceLink(s.env,{claimId:cl.claim_id,sourceId:src.sourceId,supportType,locator});return {v,cl,src};}
test('validator: no mapping is UNSOURCED',async()=>{const s=setup();assert.equal((await validator.evaluateEntryEvidence(s.env,'MLS-V10-0020')).status,'UNSOURCED');});
test('validator: contextual source is SOURCED but not verified coverage',async()=>{const s=setup();await add(s,{supportType:'contextualizes'});const r=await validator.evaluateEntryEvidence(s.env,'MLS-V10-0020');assert.equal(r.status,'SOURCED');assert.equal(r.claimsVerified,0);});
test('validator: APA readiness is computed by backend, not caller',async()=>{const s=setup();await add(s,{sourceType:'journal_article'});const r=await validator.evaluateEntryEvidence(s.env,'MLS-V10-0020',{verificationConfirmed:true,citationReady:true});assert.equal(r.status,'SOURCED');assert.equal(r.citationReady,false);assert.ok(r.reasons.includes('apa_validation_required'));});
test('validator: complete coverage cannot verify without verification event',async()=>{const s=setup();await add(s);const r=await validator.evaluateEntryEvidence(s.env,'MLS-V10-0020',{});assert.equal(r.status,'SOURCED');assert.ok(r.reasons.includes('verification_event_missing'));});
test('validator: explicit citation readiness and verification can produce VERIFIED',async()=>{const s=setup();await add(s);const r=await validator.evaluateEntryEvidence(s.env,'MLS-V10-0020',{verificationConfirmed:true,verifiedAt:'2026-09-21T12:00:00Z'});assert.equal(r.status,'VERIFIED');});
test('validator: normative claims require strong A/B source by default',async()=>{const s=setup();await add(s,{claimType:'normative',tier:'C'});const r=await validator.evaluateEntryEvidence(s.env,'MLS-V10-0020',{verificationConfirmed:true});assert.equal(r.status,'SOURCED');assert.equal(r.claimsVerified,0);});
test('validator: quotation policy requires locator',async()=>{const s=setup();await add(s,{claimType:'quotation'});let r=await validator.evaluateEntryEvidence(s.env,'MLS-V10-0020',{verificationConfirmed:true});assert.equal(r.status,'SOURCED');assert.equal(r.claimsVerified,0);const s2=setup();await add(s2,{claimType:'quotation',locator:{page:'4'}});r=await validator.evaluateEntryEvidence(s2.env,'MLS-V10-0020',{verificationConfirmed:true});assert.equal(r.status,'VERIFIED');});
test('validator: unresolved substantive contradiction blocks VERIFIED',async()=>{const s=setup();const {cl,src}=await add(s);await claims.recordConflict(s.env,{claimId:cl.claim_id,conflictType:'contradiction',context:'Discrepancia.',sourceIds:[src.sourceId]});const r=await validator.evaluateEntryEvidence(s.env,'MLS-V10-0020',{verificationConfirmed:true});assert.equal(r.status,'SOURCED');assert.ok(r.reasons.includes('unresolved_substantive_conflict'));});
test('validator: accepted regional variation does not block VERIFIED',async()=>{const s=setup();const {cl,src}=await add(s);await claims.recordConflict(s.env,{claimId:cl.claim_id,conflictType:'regional_variation',status:'accepted_variation',context:'Variación legítima.',resolution:'Se documentan ambas.',sourceIds:[src.sourceId]});assert.equal((await validator.evaluateEntryEvidence(s.env,'MLS-V10-0020',{verificationConfirmed:true})).status,'VERIFIED');});
test('validator: state persistence increments revision and rejects stale expected revision',async()=>{const s=setup();await add(s);const a=await validator.persistEvaluation(s.env,'MLS-V10-0020',{expectedEvidenceRevision:0});assert.equal(a.state.evidence_revision,1);const b=await validator.persistEvaluation(s.env,'MLS-V10-0020',{expectedEvidenceRevision:1});assert.equal(b.state.evidence_revision,2);await assert.rejects(()=>validator.persistEvaluation(s.env,'MLS-V10-0020',{expectedEvidenceRevision:1}),e=>e.code==='EVIDENCE_REVISION_CONFLICT'&&e.status===409);});
test('validator: stale state is not effective after article changes',async()=>{const s=setup();await add(s);await validator.persistEvaluation(s.env,'MLS-V10-0020',{expectedEvidenceRevision:0});s.db.prepare("UPDATE wiki_articles SET article_markdown=?,generated_at=? WHERE code=?").run('Nuevo texto','2026-09-22T00:00:00Z','MLS-V10-0020');assert.equal((await validator.effectiveState(s.env,'MLS-V10-0020')).effectiveStatus,'UNSOURCED');});
test('validator: stale state can be safely reset only with expected revision zero',async()=>{const s=setup();await add(s);await validator.persistEvaluation(s.env,'MLS-V10-0020',{expectedEvidenceRevision:0});s.db.prepare("UPDATE wiki_articles SET article_markdown=?,generated_at=? WHERE code=?").run('Texto nuevo','2026-09-22T00:00:00Z','MLS-V10-0020');const r=await validator.persistEvaluation(s.env,'MLS-V10-0020',{expectedEvidenceRevision:0});assert.equal(r.state.evidence_revision,1);assert.equal(r.state.status,'UNSOURCED');assert.equal(r.state.article_generated_at,'2026-09-22T00:00:00Z');});
