const test=require('node:test');
const assert=require('node:assert/strict');
const {DatabaseSync}=require('node:sqlite');
const registry=require('../MLS R32 EDITORIAL/evidence registry.js');
const claims=require('../MLS R32 EDITORIAL/evidence claims.js');
function setup(){
 const db=new DatabaseSync(':memory:');
 db.exec("CREATE TABLE wiki_articles(code TEXT PRIMARY KEY,article_markdown TEXT NOT NULL,generated_at TEXT NOT NULL)");
 db.prepare("INSERT INTO wiki_articles VALUES(?,?,?)").run('MLS-V10-0020','#### Regla\nLeer forma leyendo.','2026-09-21T10:00:00Z');
 const wrap=(sql,args=[])=>({sql,args,bind(...x){return wrap(sql,x)},async first(){return db.prepare(sql).get(...args)||null},async all(){return {results:db.prepare(sql).all(...args)}},async run(){const r=db.prepare(sql).run(...args);return {meta:{changes:Number(r.changes)}}}});
 const WIKI_DB={prepare:wrap,async batch(stmts){db.exec('BEGIN');try{const out=stmts.map(x=>{const r=db.prepare(x.sql).run(...x.args);return {meta:{changes:Number(r.changes)}}});db.exec('COMMIT');return out}catch(e){db.exec('ROLLBACK');throw e}}};
 return {db,env:{WIKI_DB}};
}
async function version(s){return claims.currentArticleVersion(s.env,'MLS-V10-0020');}
async function source(s,tier='A'){return (await registry.upsertSource(s.env,{sourceType:'report',authorityTier:tier,title:'Norma',institution:'Institución',publicationYear:2025})).source;}

test('claims: exact article version is required',async()=>{const s=setup(),v=await version(s);await assert.rejects(()=>claims.upsertClaim(s.env,{...v,articleHash:'0'.repeat(64),summary:'Regla',claimType:'normative'}),e=>e.code==='ARTICLE_VERSION_CONFLICT'&&e.status===409);});
test('claims: deterministic claim insert is idempotent',async()=>{const s=setup(),v=await version(s),input={...v,sectionKey:'Regla',summary:'Leer forma leyendo.',claimType:'normative',materiality:'substantial'};const a=await claims.upsertClaim(s.env,input),b=await claims.upsertClaim(s.env,input);assert.equal(a.created,true);assert.equal(b.reused,true);assert.equal(a.claim.claim_id,b.claim.claim_id);assert.equal(s.db.prepare('SELECT COUNT(*) n FROM wiki_evidence_claims').get().n,1);});
test('claims: constructed example is explicitly modeled',async()=>{const s=setup(),v=await version(s);const a=await claims.upsertClaim(s.env,{...v,summary:'María está leyendo.',claimType:'example',materiality:'constructed_example'});assert.equal(a.claim.materiality,'constructed_example');assert.equal(a.claim.status,'unverified');});
test('links: source and claim must exist and duplicate link is idempotent',async()=>{const s=setup(),v=await version(s),src=await source(s),cl=(await claims.upsertClaim(s.env,{...v,summary:'Regla',claimType:'normative'})).claim;const input={claimId:cl.claim_id,sourceId:src.sourceId,supportType:'supports',locator:{page:10,section:'2.1'},verificationMethod:'manual_source_match'};const a=await claims.upsertEvidenceLink(s.env,input),b=await claims.upsertEvidenceLink(s.env,{...input,locator:{section:'2.1',page:10}});assert.equal(a.link.link_id,b.link.link_id);assert.equal(b.reused,true);assert.equal(s.db.prepare('SELECT COUNT(*) n FROM wiki_evidence_links').get().n,1);});
test('links: unknown locator keys fail closed',async()=>{const s=setup();assert.throws(()=>claims.normalizeLocator({page:'2',inventedPage:'99'}),e=>e.code==='INVALID_LOCATOR_KEY'&&e.status===422);});
test('links: no locator is invented when absent',()=>{assert.deepEqual(claims.normalizeLocator({}),{});});
test('links: missing source fails without creating link',async()=>{const s=setup(),v=await version(s),cl=(await claims.upsertClaim(s.env,{...v,summary:'Regla'})).claim;await assert.rejects(()=>claims.upsertEvidenceLink(s.env,{claimId:cl.claim_id,sourceId:'MLS-SRC-UNKNOWN',supportType:'supports'}),e=>e.code==='SOURCE_NOT_FOUND');assert.equal(s.db.prepare('SELECT COUNT(*) n FROM wiki_evidence_links').get().n,0);});
test('conflicts: unresolved contradiction records source ids and needs review',async()=>{const s=setup(),v=await version(s),src=await source(s),cl=(await claims.upsertClaim(s.env,{...v,summary:'Regla'})).claim;const r=await claims.recordConflict(s.env,{claimId:cl.claim_id,conflictType:'contradiction',context:'Dos autoridades discrepan.',sourceIds:[src.sourceId]});assert.equal(r.conflict.needs_review,1);assert.deepEqual(JSON.parse(r.conflict.source_ids_json),[src.sourceId]);});
test('conflicts: accepted variation requires explicit resolution',async()=>{const s=setup(),v=await version(s),cl=(await claims.upsertClaim(s.env,{...v,summary:'Uso regional'})).claim;await assert.rejects(()=>claims.recordConflict(s.env,{claimId:cl.claim_id,conflictType:'regional_variation',status:'accepted_variation',context:'Varía por región.'}),e=>e.code==='CONFLICT_RESOLUTION_REQUIRED');const r=await claims.recordConflict(s.env,{claimId:cl.claim_id,conflictType:'regional_variation',status:'accepted_variation',context:'Varía por región.',resolution:'Se documentan ambas variantes.'});assert.equal(r.conflict.needs_review,0);});
test('snapshot: only current article version is returned',async()=>{const s=setup(),v=await version(s);await claims.upsertClaim(s.env,{...v,summary:'Actual'});s.db.prepare("INSERT INTO wiki_evidence_claims(claim_id,code,article_generated_at,article_hash,summary,claim_type,materiality,status,created_at) VALUES('old','MLS-V10-0020','old','old','Old','general','substantial','unverified','old')").run();const snap=await claims.entryEvidenceSnapshot(s.env,'MLS-V10-0020');assert.equal(snap.claims.length,1);assert.equal(snap.claims[0].summary,'Actual');});
