const test=require('node:test');const assert=require('node:assert/strict');const {DatabaseSync}=require('node:sqlite');
const registry=require('../MLS R32 EDITORIAL/evidence registry.js');const claims=require('../MLS R32 EDITORIAL/evidence claims.js');const validator=require('../MLS R32 EDITORIAL/evidence validator.js');const reviews=require('../MLS R32 EDITORIAL/evidence reviews.js');
function setup(){const db=new DatabaseSync(':memory:');db.exec("CREATE TABLE wiki_articles(code TEXT PRIMARY KEY,article_markdown TEXT NOT NULL,generated_at TEXT NOT NULL)");db.prepare("INSERT INTO wiki_articles VALUES(?,?,?)").run('MLS-V10-0020','#### Regla\nLeer forma leyendo.','2026-09-21T10:00:00Z');const wrap=(sql,args=[])=>({sql,args,bind(...x){return wrap(sql,x)},async first(){return db.prepare(sql).get(...args)||null},async all(){return {results:db.prepare(sql).all(...args)}},async run(){const r=db.prepare(sql).run(...args);return {meta:{changes:Number(r.changes)}}}});return {db,env:{WIKI_DB:{prepare:wrap,async batch(stmts){db.exec('BEGIN');try{const x=stmts.map(q=>{const r=db.prepare(q.sql).run(...q.args);return {meta:{changes:Number(r.changes)}}});db.exec('COMMIT');return x}catch(e){db.exec('ROLLBACK');throw e}}}}};}
async function seed(s){const v=await claims.currentArticleVersion(s.env,'MLS-V10-0020');const cl=(await claims.upsertClaim(s.env,{...v,summary:'Leer forma leyendo.',claimType:'normative',materiality:'substantial'})).claim;const src=(await registry.upsertSource(s.env,{sourceType:'report',authorityTier:'A',title:'Norma',institution:'Institución',publicationYear:2025,publisher:'Institución'})).source;await claims.upsertEvidenceLink(s.env,{claimId:cl.claim_id,sourceId:src.sourceId,supportType:'supports'});return {v,cl,src};}

test('reviews: snapshot hash is deterministic',async()=>{const s=setup();await seed(s);assert.equal(await reviews.evidenceSnapshotHash(s.env,'MLS-V10-0020'),await reviews.evidenceSnapshotHash(s.env,'MLS-V10-0020'));});
test('reviews: snapshot hash changes when evidence changes',async()=>{const s=setup();const {v}=await seed(s);const a=await reviews.evidenceSnapshotHash(s.env,'MLS-V10-0020');await claims.upsertClaim(s.env,{...v,summary:'Otro claim',claimType:'general'});const b=await reviews.evidenceSnapshotHash(s.env,'MLS-V10-0020');assert.notEqual(a,b);});
test('reviews: recordReview is append-only and idempotent',async()=>{const s=setup();await seed(s);await validator.persistEvaluation(s.env,'MLS-V10-0020',{expectedEvidenceRevision:0});const state=await validator.getEvidenceState(s.env,'MLS-V10-0020');const hash=await reviews.evidenceSnapshotHash(s.env,'MLS-V10-0020');const input={code:'MLS-V10-0020',articleGeneratedAt:state.article_generated_at,articleHash:state.article_hash,expectedEvidenceRevision:state.evidence_revision,expectedSnapshotHash:hash,reviewKind:'verification',statusBefore:'SOURCED',statusAfter:'VERIFIED',counts:{claimsTotal:1,claimsVerified:1,sourcesTotal:1,conflictsTotal:0},reviewerType:'chatgpt',verificationMethod:'manual_source_match',runId:'run-1'};const a=await reviews.recordReview(s.env,input,{now:'2026-09-21T12:00:00Z'}),b=await reviews.recordReview(s.env,input,{now:'2026-09-21T12:01:00Z'});assert.equal(a.review.review_id,b.review.review_id);assert.equal(s.db.prepare('SELECT COUNT(*) n FROM wiki_evidence_reviews').get().n,1);});
test('reviews: stale expected snapshot fails closed',async()=>{const s=setup();await seed(s);await validator.persistEvaluation(s.env,'MLS-V10-0020',{expectedEvidenceRevision:0});const st=await validator.getEvidenceState(s.env,'MLS-V10-0020');await assert.rejects(()=>reviews.recordReview(s.env,{code:'MLS-V10-0020',articleGeneratedAt:st.article_generated_at,articleHash:st.article_hash,expectedEvidenceRevision:st.evidence_revision,expectedSnapshotHash:'0'.repeat(64),reviewKind:'verification',statusAfter:'VERIFIED'}),e=>e.code==='EVIDENCE_SNAPSHOT_CONFLICT'&&e.status===409);});
test('reviews: valid review state is invalidated by later evidence change',async()=>{const s=setup();const {v}=await seed(s);await validator.persistEvaluation(s.env,'MLS-V10-0020',{expectedEvidenceRevision:0});const st=await validator.getEvidenceState(s.env,'MLS-V10-0020');const hash=await reviews.evidenceSnapshotHash(s.env,'MLS-V10-0020');await reviews.recordReview(s.env,{code:'MLS-V10-0020',articleGeneratedAt:st.article_generated_at,articleHash:st.article_hash,expectedEvidenceRevision:st.evidence_revision,expectedSnapshotHash:hash,reviewKind:'verification',statusAfter:'VERIFIED',counts:{claimsTotal:1,claimsVerified:1,sourcesTotal:1,conflictsTotal:0}},{now:'2026-09-21T12:00:00Z'});assert.ok((await reviews.validReviewState(s.env,'MLS-V10-0020')).verification);await claims.upsertClaim(s.env,{...v,summary:'Cambio posterior'});assert.equal((await reviews.validReviewState(s.env,'MLS-V10-0020')).verification,null);});
test('revisions: baseline snapshot is idempotent',async()=>{const s=setup();await registry.ensureEvidenceDb(s.env);const a=await reviews.ensureBaselineRevision(s.env,'MLS-V10-0020'),b=await reviews.ensureBaselineRevision(s.env,'MLS-V10-0020');assert.equal(a.revision.revision_id,b.revision.revision_id);assert.equal(s.db.prepare('SELECT COUNT(*) n FROM wiki_article_revisions').get().n,1);});
test('revisions: proposal does not overwrite canonical article',async()=>{const s=setup();await registry.ensureEvidenceDb(s.env);const current=await claims.currentArticleVersion(s.env,'MLS-V10-0020');const before=s.db.prepare('SELECT article_markdown FROM wiki_articles WHERE code=?').get('MLS-V10-0020').article_markdown;const p=await reviews.proposeArticleRevision(s.env,{code:'MLS-V10-0020',expectedArticleHash:current.articleHash,articleMarkdown:'#### Regla\nLeer forma *leyendo*.',changeReason:'Ajuste respaldado por evidencia.'});assert.equal(p.revision.status,'proposed');assert.equal(s.db.prepare('SELECT article_markdown FROM wiki_articles WHERE code=?').get('MLS-V10-0020').article_markdown,before);assert.equal(s.db.prepare('SELECT COUNT(*) n FROM wiki_article_revisions').get().n,2);});
test('revisions: stale article hash is rejected',async()=>{const s=setup();await registry.ensureEvidenceDb(s.env);await assert.rejects(()=>reviews.proposeArticleRevision(s.env,{code:'MLS-V10-0020',expectedArticleHash:'0'.repeat(64),articleMarkdown:'Nuevo',changeReason:'Cambio'}),e=>e.code==='ARTICLE_VERSION_CONFLICT'&&e.status===409);});
test('revisions: duplicate proposed text reuses the same revision',async()=>{const s=setup();await registry.ensureEvidenceDb(s.env);const v=await claims.currentArticleVersion(s.env,'MLS-V10-0020');const input={code:'MLS-V10-0020',expectedArticleHash:v.articleHash,articleMarkdown:'#### Regla\nTexto corregido.',changeReason:'Corrección'};const a=await reviews.proposeArticleRevision(s.env,input),b=await reviews.proposeArticleRevision(s.env,input);assert.equal(a.revision.revision_id,b.revision.revision_id);assert.equal(b.reused,true);});

test('reviews: REVIEWED requires an identified human reviewer',async()=>{
  const s=setup();await seed(s);
  await validator.persistEvaluation(s.env,'MLS-V10-0020',{expectedEvidenceRevision:0});
  let state=await validator.getEvidenceState(s.env,'MLS-V10-0020');
  await validator.verifyEntryEvidence(s.env,'MLS-V10-0020',{expectedEvidenceRevision:state.evidence_revision,reviewerType:'chatgpt',reviewer:'ChatGPT'});
  state=await validator.getEvidenceState(s.env,'MLS-V10-0020');
  await assert.rejects(
    ()=>validator.reviewEntryEvidence(s.env,'MLS-V10-0020',{expectedEvidenceRevision:state.evidence_revision,reviewerType:'chatgpt',reviewer:'ChatGPT'}),
    e=>e.code==='HUMAN_REVIEW_REQUIRED'&&e.status===422
  );
  await assert.rejects(
    ()=>validator.reviewEntryEvidence(s.env,'MLS-V10-0020',{expectedEvidenceRevision:state.evidence_revision,reviewerType:'human',reviewer:'   '}),
    e=>e.code==='HUMAN_REVIEWER_REQUIRED'&&e.status===422
  );
  const reviewed=await validator.reviewEntryEvidence(s.env,'MLS-V10-0020',{expectedEvidenceRevision:state.evidence_revision,reviewerType:'human',reviewer:'Revisor humano'});
  assert.equal(reviewed.status,'REVIEWED');
  assert.equal(reviewed.review.reviewer_type,'human');
});
