(function(root,factory){const api=factory(root);if(typeof module!=='undefined'&&module.exports)module.exports=api;if(root){root.MLSProfessorComparison=api;if(root.MLS)api.install(root.MLS);}})(typeof window!=='undefined'?window:null,function(root){'use strict';
const VERSION='1.0',MARKER='[MLS_PROFESSOR_COMPARISON 1.0]';
function clean(value){return String(value||'').replace(/\s+/g,' ').trim();}
function fold(value){return clean(value).toLocaleLowerCase();}
function slugOf(entry,meta){return clean((entry&&entry.language)||(meta&&meta.slug)||(entry&&entry.professorQuickAction&&entry.professorQuickAction.slug)||'');}
function actionIdOf(entry,meta){return clean((entry&&entry.professorQuickAction&&entry.professorQuickAction.id)||(meta&&meta.professorQuickActionId)||'');}
function detailOf(entry,meta){return clean((entry&&entry.professorQuickAction&&entry.professorQuickAction.detail)||(meta&&meta.professorComparisonDetail)||'');}
function isComparison(entry,meta){const id=actionIdOf(entry,meta);return id==='compare'||id==='difference';}
function rowsFor(slug){try{return root&&root.MLS&&root.MLS.data&&root.MLS.data.byLanguage&&Array.isArray(root.MLS.data.byLanguage[slug])?root.MLS.data.byLanguage[slug]:[]}catch(_){return [];}}
function resolveExactConcept(detail,slug,currentCode){const needle=fold(detail);if(!needle)return null;const candidates=[];for(const row of rowsFor(slug)){if(!row||String(row.code||'')===String(currentCode||''))continue;const title=clean(row.title),target=clean(row.target);if(title&&fold(title)===needle)candidates.push({row,rank:0});else if(target&&fold(target)===needle)candidates.push({row,rank:1});}if(!candidates.length)return null;candidates.sort((a,b)=>a.rank-b.rank||String(a.row.code||'').localeCompare(String(b.row.code||'')));const row=candidates[0].row;return{code:String(row.code||''),title:clean(row.title)||clean(row.target),target:clean(row.target),level:clean(row.level),chapter:String(row.chapterNum||row.chapter||'')};}
function comparisonDirective(entry,meta){if(!isComparison(entry,meta))return'';const slug=slugOf(entry,meta),id=actionIdOf(entry,meta),detail=detailOf(entry,meta),currentTitle=clean(entry&&entry.title)||clean(entry&&entry.target)||'tema actual',currentCode=clean(entry&&entry.code),resolved=detail?resolveExactConcept(detail,slug,currentCode):null;const lines=[MARKER,'Comparación conceptual especializada del Profesor IA.','Concepto X (tema actual): '+currentTitle+(currentCode?' ['+currentCode+']':'')+'.'];if(id==='compare'){lines.push('Concepto Y solicitado por el usuario: '+(detail||'no especificado')+'.');if(resolved){lines.push('Concepto Y resuelto exactamente dentro de esta misma enciclopedia: '+resolved.title+' ['+resolved.code+']'+(resolved.target?' · objetivo: '+resolved.target:'')+'.');lines.push('Cuando menciones Y, usa su título canónico cuando resulte natural para que los enlaces internos seguros del MLS puedan reconocerlo.');}else if(detail){lines.push('El concepto Y no se resolvió como título u objetivo exacto de otra entrada MLS del mismo idioma. Compáralo como concepto aportado por el usuario, pero no inventes código, enlace ni entrada MLS.');}else{lines.push('Falta el concepto Y. Pide únicamente ese dato antes de realizar la comparación.');}}else{lines.push('La acción solicita explicar una diferencia ya contenida o implícita en la entrada actual. Identifica únicamente las formas o conceptos realmente presentes; no inventes un segundo término.');}
lines.push('Estructura la respuesta con: definición breve de X; definición breve de Y cuando exista; similitudes pertinentes; diferencias por criterios paralelos; ejemplos paralelos comparables; y una síntesis de cuándo corresponde cada uno.','No presentes como equivalentes conceptos que no lo sean y no fuerces simetrías artificiales. Si una dimensión no es comparable, dilo claramente.','Mantén la variante lingüística y el sistema de escritura canónicos del idioma activo. Las diferencias regionales legítimas no son errores.','No conviertas la explicación en curso, examen o ejercicio y no modifiques el artículo publicado.','[/MLS_PROFESSOR_COMPARISON]');return lines.join('\n');}
function append(value,directive){const text=String(value||'');if(!directive||text.includes(MARKER))return text;return(text?text+'\n\n':'')+directive;}
function augmentEntry(entry,meta){if(!entry||typeof entry!=='object'||!isComparison(entry,meta))return entry&&typeof entry==='object'?{...entry}:entry;const directive=comparisonDirective(entry,meta),slug=slugOf(entry,meta),detail=detailOf(entry,meta),resolved=detail?resolveExactConcept(detail,slug,entry.code):null,out={...entry};out.professorComparisonVersion=VERSION;out.professorComparison={actionId:actionIdOf(entry,meta),slug,detail,resolved:resolved?{...resolved}:null};out.professorComparisonPrompt=directive;for(const key of['articleMarkdown','auditedBody','body','definition'])if(typeof out[key]==='string')out[key]=append(out[key],directive);if(out.plain&&typeof out.plain==='object')out.plain={...out.plain,lead:append(out.plain.lead||'',directive)};return out;}
function install(MLS){if(!MLS||!MLS.aiTutor||typeof MLS.aiTutor.open!=='function'||MLS.aiTutor.__mlsProfessorComparisonInstalled)return false;const original=MLS.aiTutor.open;MLS.aiTutor.open=function(entry,meta,...rest){const active=isComparison(entry,meta),enriched=augmentEntry(entry,meta);return original.call(this,enriched,{...(meta||{}),...(active?{professorComparisonVersion:VERSION}: {})},...rest)};MLS.aiTutor.__mlsProfessorComparisonInstalled=true;MLS.aiTutor.professorComparisonVersion=VERSION;return true;}
return{VERSION,MARKER,clean,slugOf,actionIdOf,detailOf,isComparison,resolveExactConcept,comparisonDirective,augmentEntry,install};});
