(function(root,factory){const api=factory(root);if(typeof module!=='undefined'&&module.exports)module.exports=api;if(root){root.MLSProfessorPronunciation=api;if(root.MLS)api.install(root.MLS);}})(typeof window!=='undefined'?window:null,function(root){'use strict';const VERSION='1.0',MARKER='[MLS_PROFESSOR_PRONUNCIATION 1.0]';const RULES={
'espanol-guatemala':'Pronunciación de español de Guatemala: usa IPA solo cuando ayude y explica rasgos guatemaltecos únicamente cuando sean pertinentes. No presentes rasgos de otras variedades como corrección.',
ingles:'Pronunciación de inglés: usa IPA cuando aporte claridad. Señala diferencias regionales importantes sin imponer US o UK como única pronunciación legítima.',
portugues:'Pronunciación de portugués brasileño: prioriza Brasil y explica nasalización, reducción vocálica, vocales y ritmo cuando sean pertinentes. No sustituyas la norma brasileña por portuguesa europea.',
italiano:'Pronunciación de italiano estándar: explica consonantes dobles, vocales y acento cuando correspondan, conservando la ortografía italiana como referencia principal.',
frances:'Pronunciación de francés: explica liaison, enchaînement, schwa y vocales cuando sean pertinentes, distinguiendo cuidadosamente fenómenos obligatorios, opcionales o ausentes.',
aleman:'Pronunciación de Standarddeutsch: explica vocales, consonantes y acento cuando aporten valor; variantes DACH solo como contraste relevante.',
japones:'Pronunciación de japonés: kanji y kana siguen siendo principales. Explica mora, vocal larga y geminación; pitch accent solo cuando sea pertinente. Rōmaji es apoyo limitado, nunca sustituto.',
'chino-taiwan':'Pronunciación de mandarín de Taiwán: caracteres tradicionales siguen siendo principales. Explica tonos y sandhi pertinentes; zhuyin o pinyin son apoyos, nunca sustitutos de tradicionales.',
coreano:'Pronunciación de coreano: Hangul sigue siendo principal. Explica batchim, liaison, tensificación y cambios fonológicos pertinentes. Romanización solo como apoyo limitado.',
ruso:'Pronunciación de ruso: cirílico sigue siendo principal. Marca acento léxico cuando sea pedagógicamente útil y explica reducción vocálica y palatalización cuando correspondan. Transliteración solo como apoyo.'};
function slugOf(entry,meta){return String((entry&&entry.language)||(meta&&meta.slug)||(meta&&meta.professorQuickAction&&meta.professorQuickAction.slug)||'').trim();}function ruleFor(slug){return RULES[slug]||'Explica la pronunciación desde las convenciones propias del idioma objetivo. Conserva su escritura canónica como principal y usa romanización o transliteración solo como apoyo cuando sea realmente útil.';}function isPronunciation(meta){const id=String(meta&&meta.professorQuickActionId||'');return id==='pronunciation'||/-pronunciation$/.test(id)||id==='ja-reading'||id==='zh-tones'||id==='ko-batchim'||id==='ru-stress';}function directiveFor(slug){return[MARKER,ruleFor(slug),'No modifiques el artículo publicado. Esta capa explica pronunciación y no altera el motor TTS.','[/MLS_PROFESSOR_PRONUNCIATION]'].join('\n');}function append(value,d){const text=String(value||'');return text.includes(MARKER)?text:(text?text+'\n\n':'')+d;}function augmentEntry(entry,meta){if(!entry||typeof entry!=='object'||!isPronunciation(meta))return entry&&typeof entry==='object'?{...entry}:entry;const slug=slugOf(entry,meta),d=directiveFor(slug),out={...entry,professorPronunciationVersion:VERSION,professorPronunciationPrompt:d};for(const key of['articleMarkdown','auditedBody','body','definition'])if(typeof out[key]==='string')out[key]=append(out[key],d);if(out.plain&&typeof out.plain==='object')out.plain={...out.plain,lead:append(out.plain.lead||'',d)};return out;}function install(MLS){if(!MLS||!MLS.aiTutor||typeof MLS.aiTutor.open!=='function'||MLS.aiTutor.__mlsProfessorPronunciationInstalled)return false;const original=MLS.aiTutor.open;MLS.aiTutor.open=function(entry,meta,...rest){const active=isPronunciation(meta);return original.call(this,augmentEntry(entry,meta),{...(meta||{}),...(active?{professorPronunciationVersion:VERSION}: {})},...rest)};MLS.aiTutor.__mlsProfessorPronunciationInstalled=true;MLS.aiTutor.professorPronunciationVersion=VERSION;return true;}return{VERSION,RULES,slugOf,ruleFor,isPronunciation,directiveFor,augmentEntry,install};});