(function(root,factory){const api=factory(root);if(typeof module!=='undefined'&&module.exports)module.exports=api;if(root){root.MLSProfessorObservability=api;if(root.MLS)api.install(root.MLS);}})(typeof window!=='undefined'?window:null,function(root){'use strict';
const VERSION='1.0',STORAGE_KEY='mlsProfessorObservabilityV1';
const EVENTS=Object.freeze({open:'opens',request:'requests',success:'successes',failure:'failures',retry:'retries',cancellation:'cancellations'});
const ERROR_STATES=new Set(['offline','quota','retry','temporary-error']);
function bucket(){return{opens:0,requests:0,successes:0,failures:0,retries:0,cancellations:0,totalMs:0};}
function blank(){return{version:VERSION,totals:bucket(),dimensions:{language:{},action:{},depth:{},length:{}}};}
function safeKey(value,fallback){const text=String(value||fallback||'none').toLowerCase().trim().replace(/[^a-z0-9áéíóúüñ-]+/gi,'-').replace(/^-+|-+$/g,'').slice(0,40);return text||fallback||'none';}
function metaFrom(entry,meta){const prefs=(meta&&meta.professorPreferences)||(entry&&entry.professorPreferences)||{};return{language:safeKey((entry&&entry.language)||(meta&&meta.slug),'neutral'),action:safeKey((meta&&meta.professorQuickActionId)||(entry&&entry.professorQuickAction&&entry.professorQuickAction.id),'manual'),depth:safeKey(prefs.depth,'normal'),length:safeKey(prefs.length,'normal')};}
function numericBucket(value){const out=bucket(),src=value&&typeof value==='object'?value:{};for(const key of Object.keys(out)){const n=Number(src[key]);out[key]=Number.isFinite(n)&&n>=0?n:0;}return out;}
function normalize(raw){const out=blank(),src=raw&&typeof raw==='object'?raw:{};out.totals=numericBucket(src.totals);for(const dim of Object.keys(out.dimensions)){const source=src.dimensions&&src.dimensions[dim];if(!source||typeof source!=='object')continue;for(const [key,value] of Object.entries(source).slice(0,100))out.dimensions[dim][safeKey(key,'other')]=numericBucket(value);}return out;}
function load(){try{if(!root||!root.localStorage)return blank();return normalize(JSON.parse(root.localStorage.getItem(STORAGE_KEY)||'{}'));}catch{return blank();}}
function save(stats){const clean=normalize(stats);try{if(root&&root.localStorage)root.localStorage.setItem(STORAGE_KEY,JSON.stringify(clean));}catch{}return clean;}
function reset(){const clean=blank();try{if(root&&root.localStorage)root.localStorage.removeItem(STORAGE_KEY);}catch{}return clean;}
function recordInto(stats,event,meta,elapsedMs){const key=EVENTS[event];if(!key)return normalize(stats);const out=normalize(stats),info=meta||{};out.totals[key]++;if((event==='success'||event==='failure'||event==='cancellation')&&Number.isFinite(Number(elapsedMs)))out.totals.totalMs+=Math.max(0,Math.round(Number(elapsedMs)));for(const dim of Object.keys(out.dimensions)){const value=safeKey(info[dim],dim==='language'?'neutral':dim==='action'?'manual':'normal');out.dimensions[dim][value]=numericBucket(out.dimensions[dim][value]);out.dimensions[dim][value][key]++;if((event==='success'||event==='failure'||event==='cancellation')&&Number.isFinite(Number(elapsedMs)))out.dimensions[dim][value].totalMs+=Math.max(0,Math.round(Number(elapsedMs)));}return out;}
function record(event,meta,elapsedMs){return save(recordInto(load(),event,meta,elapsedMs));}
function averageMs(stats){const s=normalize(stats),done=s.totals.successes+s.totals.failures+s.totals.cancellations;return done?Math.round(s.totals.totalMs/done):0;}
function currentState(modal){if(!modal)return'ready';if(modal.dataset&&modal.dataset.aiState)return String(modal.dataset.aiState);if(root&&root.MLSProfessorVisualStates&&typeof root.MLSProfessorVisualStates.applyState==='function')return root.MLSProfessorVisualStates.applyState(modal);return'ready';}
function observeDialog(modal,meta){if(!modal||modal.__mlsProfessorObservabilityObserved)return false;let previous=currentState(modal),pending=false,failed=false,startedAt=0,closed=false;const now=()=>root&&root.performance&&typeof root.performance.now==='function'?root.performance.now():Date.now();const finish=event=>{if(!pending)return;record(event,meta,Math.max(0,now()-startedAt));pending=false;failed=event==='failure';};const evaluate=()=>{const state=currentState(modal);if(state===previous)return;if(state==='thinking'&&!pending){pending=true;failed=false;startedAt=now();record('request',meta);}else if(ERROR_STATES.has(state)&&pending){finish('failure');}else if(state==='ready'&&pending&&!failed){finish('success');}previous=state;};const click=event=>{const target=event&&event.target;if(target&&target.closest&&target.closest('[data-ai-retry]'))record('retry',meta);};modal.addEventListener&&modal.addEventListener('click',click,true);const Observer=root&&root.MutationObserver;if(typeof Observer==='function'){const observer=new Observer(evaluate);observer.observe(modal,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['class','data-ai-state','data-ai-busy','hidden']});modal.__mlsProfessorObservabilityObserver=observer;const parentObserver=new Observer(()=>{if(!closed&&!modal.isConnected){closed=true;if(pending)finish('cancellation');observer.disconnect();parentObserver.disconnect();}});if(root.document&&root.document.body)parentObserver.observe(root.document.body,{childList:true,subtree:true});modal.__mlsProfessorObservabilityParentObserver=parentObserver;}modal.__mlsProfessorObservabilityObserved=true;return true;}
function install(MLS){if(!MLS||!MLS.aiTutor||typeof MLS.aiTutor.open!=='function'||MLS.aiTutor.__mlsProfessorObservabilityInstalled)return false;const original=MLS.aiTutor.open;MLS.aiTutor.open=function(entry,meta,...rest){const info=metaFrom(entry,meta);record('open',info);const result=original.call(this,entry,meta,...rest);const attach=()=>{const modal=root&&root.document&&root.document.getElementById('aiTutorModal');if(modal)observeDialog(modal,info);};if(root&&typeof root.queueMicrotask==='function')root.queueMicrotask(attach);else if(root&&typeof root.setTimeout==='function')root.setTimeout(attach,0);else attach();return result;};MLS.aiTutor.__mlsProfessorObservabilityInstalled=true;MLS.aiTutor.professorObservabilityVersion=VERSION;MLS.aiTutor.professorObservabilitySnapshot=()=>{const stats=load();return{...stats,averageMs:averageMs(stats)};};MLS.aiTutor.resetProfessorObservability=reset;return true;}
return{VERSION,STORAGE_KEY,EVENTS,ERROR_STATES,bucket,blank,safeKey,metaFrom,normalize,load,save,reset,recordInto,record,averageMs,currentState,observeDialog,install};});
