const assert=require('node:assert/strict');
const fs=require('node:fs');
const pool=require('../MLS R32 EDITORIAL/r44/pool-manifest.json');
const s=JSON.parse(fs.readFileSync(0,'utf8'));
assert.equal(s.status,'ACTIVE');
assert.equal(s.controlPlane,'CLOUDFLARE_D1');
assert.equal(s.productionMode,'PARALLEL_HOT_PATH');
assert.equal(s.globalProductionMutex,false);
assert.equal(s.githubHotPathWrites,false);
assert.equal(s.maxActiveLeases,128);
assert.equal(s.leaseTtlSeconds,300);
assert.equal(s.meta.pool_schema,pool.schema);
assert.equal(Number(s.meta.pool_ticket_count),pool.ticketCount);
assert.equal(Number(s.meta.pool_entry_count),pool.entryCount);
assert.equal(s.meta.base_commit,pool.source.emergencyBaseCommit);
assert.equal(s.meta.content_manifest_blob,pool.source.contentManifestBlob);
assert.equal(s.meta.pool_manifest_sha256,require('node:crypto').createHash('sha256').update(fs.readFileSync('MLS R32 EDITORIAL/r44/pool-manifest.json')).digest('hex'));
assert.equal(['queued','leased','audited','verified','quarantined'].reduce((n,k)=>n+s.counts[k],0),pool.ticketCount);
assert(s.counts.recoverable<=s.counts.leased);
console.log('R44_POOL_2_STATUS_VERIFIED');
